### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by JINKE-BETAWA** [JINKE-BETAWA/protospace-32593#1]
# URL
https://protospace-32593.herokuapp.com/

**Comment by eeee-0000** [comment]
JINKE-BETAWAさん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・ログアウト状態で、遷移可能な条件のページに遷移できない。
→ログアウト状態でも、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるようにしましょう。現在は下記画面にしか遷移できない状態となっております。
![image](https://user-images.githubusercontent.com/62004107/102448413-6bde1580-4075-11eb-96d0-797284c085be.png)

・ログイン時には、トップページに「こんにちは、〇〇さん」と表示されてない。
→現在、「こんにちは、〇〇」と表示されます。
ログイン時には、トップページに「こんにちは、〇〇さん」と表示されるようにしましょう。
![image](https://user-images.githubusercontent.com/62004107/102448479-9203b580-4075-11eb-9511-37c77a146734.png)


・他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、編集ページに遷移する。
→ユーザー「課長」でログイン時に、別ユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、編集ページに遷移しました。
他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう。

▼確認したURL
![image](https://user-images.githubusercontent.com/62004107/102448682-063e5900-4076-11eb-970b-cccada62276a.png)

▼遷移した画面
![image](https://user-images.githubusercontent.com/62004107/102448784-3dad0580-4076-11eb-9060-eb1ea673dd3d.png)


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by JINKE-BETAWA** [comment]
了解しました。確認します。

**Comment by JINKE-BETAWA** [comment]
以下、修正完了しました。確認お願いします。

①ログアウト時の遷移可能ページの修正
②indexの名称変更
③他ユーザーのeditアクセス拒否

# URL
https://protospace-32593.herokuapp.com/

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by JINKE-BETAWA** [comment]
ありがとうございます。
